[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7F7F7F"
blue = "#5C5CFF"
cyan = "#00FFFF"
green = "#00FF00"
magenta = "#FF00FF"
red = "#FF0000"
white = "#FFFFFF"
yellow = "#FFFF00"

[colors.normal]
black = "#000000"
blue = "#0000CD"
cyan = "#00CDCD"
green = "#00CD00"
magenta = "#CD00CD"
red = "#CD0000"
white = "#E5E5E5"
yellow = "#CDCD00"

[colors.primary]
background = "#000000"
foreground = "#B0B0B0"

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Book"

[window]
decorations = "full"
decorations_theme_variant = "none"
dynamic_title = true
opacity = 0.75

[window.dimensions]
columns = 80
lines = 56
